import os

SECRET_KEY = 'secret-here'
DATABASE_URL = 'db.sqlite'
OVERLORD_NAME = 'DreadPirateRoberts'
OVERLORD_PWD = 'secret'
#SIMPLELOGIN_BLUEPRINT = os.getenv('SIMPLELOGIN_BLUEPRINT')
#SIMPLELOGIN_LOGIN_URL = os.getenv('SIMPLELOGIN_LOGIN_URL')
#SIMPLELOGIN_LOGOUT_URL = os.getenv('SIMPLELOGIN_LOGOUT_URL')
#SIMPLELOGIN_HOME_URL = os.getenv('SIMPLELOGIN_HOME_URL')
